### ISSUE TITLE
az containerapp create fails with "argument of type NoneType is not iterable"

### ISSUE THREAD

**Issue by bebound** [bebound/azure-cli#9]
## Describe the bug

`az containerapp create` fails with name, resource group, subscription params.

**Command Name**
`az containerapp create
Extension Name: containerapp. Version: 0.3.16.`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/Users/gs/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 28, in _polish_bad_errors
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.43.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/Users/gs/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 573, in create_containerapp
    handle_raw_exception(e)
  File "/Users/gs/.azure/cliextensions/containerapp/azext_containerapp/_client_factory.py", line 54, in handle_raw_exception
    raise e
  File "/Users/gs/.azure/cliextensions/containerapp/azext_containerapp/custom.py", line 563, in create_containerapp
    if "configuration" in r["properties"] and "ingress" in r["properties"]["configuration"] and "fqdn" in r["properties"]["configuration"]["ingress"]:
TypeError: argument of type 'NoneType' is not iterable

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az containerapp create -n myName -g myGroup --subscription mySub --environment myEnv`

## Expected Behavior

A containerapp is created

## Environment Summary
```
macOS-13.2-arm64-arm-64bit, Darwin 22.3.0
Python 3.10.9
Copy from `https://github.com/Azure/azure-cli/issues/25012`

**Comment by bebound** [comment]
Error stack is not the same
